
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ковалев Владислав
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        removeBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTA = new javax.swing.JTextArea();
        pathTF = new javax.swing.JTextField();
        createBTN = new javax.swing.JButton();
        renameBTN = new javax.swing.JButton();
        readBTN = new javax.swing.JButton();
        writeBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Путь к файлу");

        removeBTN.setText("удалить");
        removeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBTNActionPerformed(evt);
            }
        });

        contentTA.setColumns(20);
        contentTA.setRows(5);
        jScrollPane1.setViewportView(contentTA);

        createBTN.setText("создать");
        createBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBTNActionPerformed(evt);
            }
        });

        renameBTN.setText("переименовать");
        renameBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameBTNActionPerformed(evt);
            }
        });

        readBTN.setText("прочитать");

        writeBTN.setText("записать");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(renameBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(readBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(writeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(pathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(createBTN)
                        .addGap(18, 18, 18)
                        .addComponent(removeBTN)
                        .addGap(29, 29, 29)
                        .addComponent(renameBTN)
                        .addGap(28, 28, 28)
                        .addComponent(readBTN)
                        .addGap(33, 33, 33)
                        .addComponent(writeBTN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBTNActionPerformed
        createNewFile(pathTF.getText());
    }//GEN-LAST:event_createBTNActionPerformed

    private void removeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBTNActionPerformed
        removeFile(pathTF.getText());
    }//GEN-LAST:event_removeBTNActionPerformed

    private void renameBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameBTNActionPerformed
        renameFile(pathTF.getText());
    }//GEN-LAST:event_renameBTNActionPerformed

    private void error(String text){
        JOptionPane.showMessageDialog(null, text, "Ошибка", 0);
    }
    
    private void success(String text){
        JOptionPane.showMessageDialog(null, text, "Ура, заработало", 1);
    }
    
    private String readPath(String path){
        path = path.trim();
        if (path.isEmpty()){
            error("Не введён путь");
            return null;
        }else{
            return path;
        }
    }
    
    private File fileExists(String path){
        path = readPath(path);
        if (path == null) return null;
        File file = new File(path);
        if (file.exists()){
            return file;
        }else{
            error("404 File not Found");
            return null;
        }
    }
    
    private void createNewFile(String path){
        path = readPath(path);
        if (path == null) return;
        File file = new File(path);
        try {
            file.createNewFile();
            success("Файл успешно создан");
        } catch (IOException ex) {
            error("Ошибка при создании файла");
        }
    }
    
    private void removeFile(String path){
        File file = fileExists(path);
        if (file == null) return;
        file.delete();
        success("Файл успешно удалён");
    }
    
    private void renameFile(String path){
        File file = fileExists(path);
        if (file == null) return;
        String new_name = JOptionPane.showInputDialog("Введите новое имя");
        if (new_name == null) return;
        new_name = readPath(new_name);
        if (new_name == null) return;
        File nf = new File(file.getParent() + "\\" + new_name);
        if (file.renameTo(nf)){
            success("Файл успешно переименован");
        }else{
            error("Ошибка при переименовании");
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea contentTA;
    private javax.swing.JButton createBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pathTF;
    private javax.swing.JButton readBTN;
    private javax.swing.JButton removeBTN;
    private javax.swing.JButton renameBTN;
    private javax.swing.JButton writeBTN;
    // End of variables declaration//GEN-END:variables
}
